name: ciscobillapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel/Abel-Regular.ttf
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton/Anton-Regular.ttf
    - family: Noto
      fonts:
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Regular.otf
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Thin.otf
          weight: 100
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Black.otf
          weight: 900
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Medium.otf
          weight: 500
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald/Oswald-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Oswald/Oswald-Bold.ttf
          weight: 700
        - asset: assets/fonts/Oswald/Oswald-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Oswald/Oswald-Light.ttf
          weight: 300
        - asset: assets/fonts/Oswald/Oswald-Medium.ttf
          weight: 500
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
          weight: 500
    - family: SourceSerif
      fonts:
        - asset: assets/fonts/Source_Serif_Pro/SourceSerifPro-Regular.ttf
        - asset: assets/fonts/Source_Serif_Pro/SourceSerifPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/Source_Serif_Pro/SourceSerifPro-SemiBold.ttf
          weight: 600

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
